### ISSUE TITLE
Migrate Error - "Hmmmm. That file doesn't look right"

### ISSUE THREAD

**Issue by saigonwheat** [aeharding/wefwef#104]
Trying to utilize the the "Migrate Apollo export" feature. Following the steps outlined, it just gives the error "Hmmmm. That file doesn't look right"

The Apollo app exported the file name as "local-data.json"

**Comment by aeharding** [comment]
If you're comfortable with it, please email to hello@wefwef.app.

I only had one file to test with 😅

**Comment by saigonwheat** [comment]
@aeharding just sent you the file via email.

**Comment by aeharding** [comment]
Should be resolved in 0.8.2, try it out!
