### ISSUE TITLE
“Huh, u/<myusername>@lemmy.world doesn’t exist. Mysterious…”

### ISSUE THREAD

**Issue by peruginiandrea** [aeharding/wefwef#107]
This happens with my account on lemmy.world (but not on beehaw.org) when going to my profile tab. Other than that, everything else still seems to work. (It doesn’t literally say \<myusername> to be clear, that was a placeholder)

**Comment by aeharding** [comment]
Hi @peruginiandrea, are you on 0.8.2?

And yeah, it probably shouldn't show this error for your own user, even if the request fails

**Comment by peruginiandrea** [comment]
You've just made me realize that I'm apparently on 0.8.1 according to the "Check for updates" section on the webapp, but I've just done `git pull` a few moments ago and I'm `Already up to date`.

I'm using Docker built from source as per your instructions.

**Comment by aeharding** [comment]
This should be resolved in 0.9. The alert should only appear if the user actually isn't found, not if the server is down
