### ISSUE TITLE
App doesn't update

### ISSUE THREAD

**Issue by KarkanAlzwayed** [aeharding/wefwef#113]
Not sure if this is intentional or not, but the app is still on 0.7, and the releases page shows last version is 0.8.2. I tried to update from within the app, but it shows up to date. 
System: android
Browser: brave

**Comment by aeharding** [comment]
Can you try removing from your homescreen and re-adding?

**Comment by aeharding** [comment]
Also I noticed that w.opnxng.com is running 0.7 still. If you want the latest updates, please double check you're installing from https://wefwef.app.

**Comment by KarkanAlzwayed** [comment]
> Also I noticed that w.opnxng.com is running 0.7 still. If you want the latest updates, please double check you're installing from https://wefwef.app.

Yup. It was from w.opnxng. Removed it and installed from the official one and got the update. I was recommended the other one because the official one kept failing to fetch posts.

**Comment by KarkanAlzwayed** [comment]
Yup, it is now back to "failed to fetch posts". I'm going to have to go back to the opennxg one :/

**Comment by aeharding** [comment]
If you're using lemmy.world, that's probably why. Closing this issue though as the root problem was resolved
