### ISSUE TITLE
Save post/comment functionality?

### ISSUE THREAD

**Issue by driftywinds** [aeharding/wefwef#114]
I see the icon for saving a post but the button is not functional, and comments on the other hand don't even have the placeholder button for saving. Is there scope for saving posts and comments to be implemented anytime soon?

**Comment by httpjamesm** [comment]
Saving is currently marked as todo in the code. If this isn't picked up by tomorrow night, I can start working on it.

**Comment by aeharding** [comment]
@httpjamesm, I am going to be working on saving posts as part of #57

**Comment by aeharding** [comment]
Closing as duplicate
