### ISSUE TITLE
Please allow users to change the font size

### ISSUE THREAD

**Issue by oz42** [aeharding/wefwef#12]
Font size is too small on my iPad Air. Yes, I'm that old.

**Comment by aeharding** [comment]
Thanks for the issue! A font size selector will be coming.

**Comment by aeharding** [comment]
@oz42 curious, do you use a larger system font? If so, as a quick fix (until manual font size selector is implemented), I could just add support for the system font size.

**Comment by oz42** [comment]
Yes, I am using a larger font size.

**Comment by masukomi** [comment]
some notes for anyone who works on this but isn't familiar with text accessibility things. 

zoom != increasing font size. These are different mechanics. Also, note that Chrome and Firefox both allow you to set a MINIMUM font size. I run mine at 20 default and 18 minimum, meaning no matter how small you make some text, some of us will see it bigger and that _will_ effect flow.  

also the necessary reminder that eyes getting worse as you age is a common thing for humans and this type of work is just insuring your future and usability by older folks (not even "old" just... _older_)
