### ISSUE TITLE
Create a button to auto join/follow/whatever its called the communities that come from the export 

### ISSUE THREAD

**Issue by Leopere** [aeharding/wefwef#122]
It would be ideal to allow me to just hit one button marked "I don't care just subscribe" and let me clean up the mess later I don't want to manually make these assessments at all I just want to get the hell off reddit.  Thanks heaps for this amazing alternative by the way!!

**Comment by aeharding** [comment]
Haha. Thanks for the request, but there might be rate limit/perf concerns with this.

I'm going to close this. But thanks again.

**Comment by Leopere** [comment]
That's fair I'm was subscribed to an absolutely wild number of subs across a number of accounts and migrating is going to be pretty arduous.
