### ISSUE TITLE
Scrolling gets very janky at times forcing a restart

### ISSUE THREAD

**Issue by adarsh1001** [aeharding/wefwef#126]
I'm using this app as a PWA (0.8.2) through Firefox (latest) on Android and noticed that scrolling gets very janky sometimes all of a sudden and the only way to then fix it is to kill the app and start again. 

https://github.com/aeharding/wefwef/assets/8820038/e211f420-443a-4b5b-9076-7e220aa2b05f

**Comment by aeharding** [comment]
Hi there! Thanks for the issue but a reliable reproduction is needed to solve this. If you can determine specific reproduction steps that causes this then please open another issue 🙂
