### ISSUE TITLE
Dark mode doesn't work on android

### ISSUE THREAD

**Issue by bananaTHEkid** [aeharding/wefwef#128]
There is no dark mode setting in the app and the app doesn't use the system setting when using the pwa

**Comment by httpjamesm** [comment]
Which browser are you on? If you're on Brave browser, you'll need to set fingerprinting protection to "Block fingerprinting" or lower for it to pass the theme you're using.

**Comment by aeharding** [comment]
0.9.0 has support for custom dark mode, so I'm going to close this. Feel free to open a discussion on device configuration issues for auto dark mode.
