### ISSUE TITLE
Setting to have comments collapsed by default

### ISSUE THREAD

**Issue by aperson** [aeharding/wefwef#130]
It would be great if comment threads could be collapsed by default via a setting.

**Comment by aeharding** [comment]
Do you mean everything after the root level?

**Comment by aperson** [comment]
Yes.  I prefer to have to expand comments than to have to collapse them.  Less clutter that way.

**Comment by tpkee** [comment]
pr is almost ready (yes I have a lot of free time today)

**Comment by aperson** [comment]
You're amazing!

**Comment by aperson** [comment]
Works awesome!
