### ISSUE TITLE
Keyboard not visible on PWA iOS

### ISSUE THREAD

**Issue by cloventt** [aeharding/wefwef#148]
![IMG_2376](https://github.com/aeharding/wefwef/assets/2382054/defa902d-c08b-4e2c-9f1c-e58c141da7ef)

When replying to a comment in iOS PWA, the keyboard is below the bottom of the screen and cannot be typed with.

I’m using wefwef 0.9.1 on iOS 16.6 beta on iPhone 13 Pro Max.

**Comment by aeharding** [comment]
Hello! Please restart your device. If still a problem, please report the bug to Apple as its a beta iOS
