### ISSUE TITLE
Please allow 2FA Prompt on login page

### ISSUE THREAD

**Issue by GL-Red** [aeharding/wefwef#15]
Attempting to sign-in to the instance Lemmy.fmhy.ml, but it gives me an error. It’s because the 2FA prompt is unavailable. I have disabled 2FA and I’m signed in.

Tried from both iPhone and iPad on iOS 16.5.1
Error says “check credentials and try again” 

Thank you for your time and love the site!

**Comment by aeharding** [comment]
Hi thanks! I was actually going to add this yesterday but I added 2fa to one of my accounts and got locked out... 😅

I'll try again shortly!

**Comment by GL-Red** [comment]
> Hi thanks! I was actually going to add this yesterday but I added 2fa to one of my accounts and got locked out... 😅
> 
> I'll try again shortly!

Thank you!

**Comment by aeharding** [comment]
Resolved in latest release. May need to force quite app a couple time to reflect changes!

**Comment by fschaupp** [comment]
Hi, can someone confirm this is still working?
At least for me it didn't work on lemmy.ml today...
@aeharding
