### ISSUE TITLE
New Instance wefwef.nohost.network

### ISSUE THREAD

**Issue by nohoster** [aeharding/wefwef#153]
Hello, I decided to host a wefwef instance since libreddit might be doomed. It's at https://wefwef.nohost.network . Country Mexico. You can add it if you want. Keep up up the amazing work.

**Comment by aeharding** [comment]
Hi, thanks! Do you have a privacy policy and/or about page I can link to?

Thanks

**Comment by nohoster** [comment]
Not at the moment, but you can add admin@nohost.network to the contact information

**Comment by aeharding** [comment]
I appreciate you hosting - but because wefwef proxies user data I think a privacy policy and/or about page would be best.

Closing for now, but feel free to reopen if that becomes a thing.

Thank you!
