### ISSUE TITLE
Long press on an image should give an option to save

### ISSUE THREAD

**Issue by eyebrowsoffire** [aeharding/wefwef#154]
As of right now, I can't figure out a way to save/copy an image from the app, I have to open it in Safari first in the default Lemmy UI. In Apollo (iOS), long press would bring up a context menu for saving/copying the image. Could we get that implemented in wefwef?

**Comment by aeharding** [comment]
Thank you! If you have a privacy policy/about link I'd happily accept a PR to the readme.

**Comment by bdonvr** [comment]
> Thank you! If you have a privacy policy/about link I'd happily accept a PR to the readme.

I think you replied to the wrong thing here

**Comment by aeharding** [comment]
Yes. Probably an ellipse in the image previewer that would bring up options to share/download.

**Comment by eyebrowsoffire** [comment]
Awesome! Thanks for what quick turnaround! ❤️
