### ISSUE TITLE
iOS Keyboard doesn't show up for commenting

### ISSUE THREAD

**Issue by mbentley** [aeharding/wefwef#157]
Running iOS 16.5.1 on my iPhone 14 Pro and the keyboard never shows up when I try to comment. I have wefwef installed as an app.  Thought maybe I am missing something.  Here's a quick video:

https://github.com/aeharding/wefwef/assets/414445/5dfa004a-579b-41dd-acc1-e3ba169c335c

**Comment by bdonvr** [comment]
If I recall correctly this is an iOS bug with PWAs. Users have said rebooting your iPhone will fix this.

**Comment by mbentley** [comment]
Indeed it did, thanks!  I just realized I didn't think to search closed issues as well.
