### ISSUE TITLE
[Feature request] Tap community name to bring up search and favorites

### ISSUE THREAD

**Issue by robertafreese** [aeharding/wefwef#159]
Feature in Apollo I used a lot, tapping the community name brought up in a search box with auto complete on 'known' communities and a list of favorites (see #67 Favourite communities)

**Comment by aeharding** [comment]
Thanks. I have initial work on this in a local feature branch, but haven't had the time to resume.

**Comment by aeharding** [comment]
This should be (mostly) done so I'm going to close. Support for favorites in the switcher will come later :)
