### ISSUE TITLE
[feature request] next / back and root / parent buttons like in RIF

### ISSUE THREAD

**Issue by CrashTD** [aeharding/wefwef#165]
The for me most important feature of Reddit is Fun was the navigation buttons in comment chains.

Tap a top level comment to see **NEXT** and **PREVIOUS** to jump between them.

Tap a comment below a top comment to get 2 extra buttons. **PARENT** jumps to the top of the sub-chain you are in. **ROOT** jumps to the very top of the chain you are in.

Example

- **Topcomment 1** < if you are here. **NEXT** / **PREVIOUS** jumps between top comments.
  - Comment 1
    - Subcomment < if you are here. **PARENT** jumps to comment 1. **ROOT** jumps to Topcomment 1. **NEXT** / **PREVIOUS** jumps betwen subcomments
    - Subcomment 2
    - Subcomment 3
  - Comment 2
- **Topcomment 2**

However this would make it necessary to change the behaviour of collapsing comments when one taps on it (which i think is questionable anyway)

**Comment by aeharding** [comment]
Hi there! Thanks for the feature request. However we are going to make nav comments work like it did in Apollo.

- [x] Long swipe any comment to collapse whole chain
- [x] Tap comment to collapse, and
- [ ] A [fab](https://ionicframework.com/docs/api/fab) button that allows you to jump next/previous root comment

Only the last one is not done yet.
