### ISSUE TITLE
1 more replies

### ISSUE THREAD

**Issue by aeharding** [aeharding/wefwef#184]
<img width="234" alt="image" src="https://github.com/aeharding/wefwef/assets/2166114/1aab2a1d-5791-442b-ae08-9c23efda2706">

fix singular

**Comment by rsammelson** [comment]
@aeharding I can make a PR for this if you want.

**Comment by aeharding** [comment]
@rsammelson appreciated!

**Comment by bdonvr** [comment]
> @aeharding I can make a PR for this if you want.

Oh sorry! I had started working on this before your comment :(
