### ISSUE TITLE
Swiping to upvote one post upvoted another instead

### ISSUE THREAD

**Issue by aperson** [aeharding/wefwef#194]
Video of it happening here: https://youtu.be/9KR_7Sx9P58

I will edit with links to the posts in question in a minute.

Edit:

I no longer can reproduce this, so do with this what you will.

Edit2:

I got it to happen on a different set of posts.

**Comment by GitBarns** [comment]
https://github.com/aeharding/wefwef/assets/136652942/4c37670c-5b8a-40ee-b146-ac1f464031cc

**Comment by aeharding** [comment]
I believe I have a fix, but this is flakey so I'm going to push a release and I would really appreciate follow up if it is resolved 😊

**Comment by aeharding** [comment]
(Closing for now, please reopen if it happens again)
