### ISSUE TITLE
Video full screening while in homepage

### ISSUE THREAD

**Issue by ooosssay** [aeharding/wefwef#199]
When I press play on a video, the video will full screen while in the Home Screen but it will also open up the post at the same time. It will also full screen when going back.

**Comment by ooosssay** [comment]
https://github.com/ooosssay/Test/assets/129241633/4cc93bf1-707e-42af-b1f2-9c42a19870ab

**Comment by aeharding** [comment]
Thanks. Probably needs a e.stopPropagation() somewhere

**Comment by aeharding** [comment]
This should be resolved by #288
