### ISSUE TITLE
Failing to log in with programming.dev

### ISSUE THREAD

**Issue by danielducharme** [aeharding/wefwef#201]
Up until version 0.11.0 I was having no trouble using the other login url and utilizing my account on programming.dev. When I updated to 0.11.0 my feed stopped updating so I tested logging out and back in and now am getting the message “Problem connecting to programming.dev. Please try again.”

**Comment by aeharding** [comment]
Hi there!

It looks like programming.dev has turned on Cloudflare that's blocking wefwef.app.

You can try asking your server administrator to whitelist IP 64.227.15.201
