### ISSUE TITLE
Is it possible to have just a Sort type label or a clearer icon? 

### ISSUE THREAD

**Issue by tpkee** [aeharding/wefwef#221]
<img width="1440" alt="image" src="https://github.com/aeharding/wefwef/assets/89136677/20d5529e-7e69-44fb-8f86-3e50aaf4dd13">

Right now the icon varies based on the selected sort method which is quite confusing in my opinion

**Comment by aeharding** [comment]
This is intended behavior. If you have a better icon idea from ion-icons for a specific sort, please open a discussion for it.

https://ionic.io/ionicons

Thanks!
