### ISSUE TITLE
Please check your credentials and try again

### ISSUE THREAD

**Issue by dzervas** [aeharding/wefwef#23]
I'm trying to login (iOS, app "installed" to home screen) to lemmy.world and I always get "please check your credentials and try again". I'm sure that my credentials are correct (password manager) and I even changed my password and tried again - no luck.

I don't have access to any kind of logs so :shrug: it's just a "this doesn't work for me" issue - hope you have some kind of insight

thank you for this, it's a very good idea - fills the gap between now and proper ios app perfectly!

**Comment by aeharding** [comment]
Do you have 2fa enabled? And if you can provide, instance name? Thanks very much!

**Comment by soundmonster** [comment]
Seeing the same problem with my lemmy.world account.

**Comment by aeharding** [comment]
It's possible lemmy.world was temporarily down. I could probably add better error messages in that case.

**Comment by aeharding** [comment]
Closing in favor of #26

**Comment by dzervas** [comment]
btw I still get the same message although lemmy.world is up

**Comment by dzervas** [comment]
I tried another client and the actual problem was that my email was not verified! Verified it and now it works great! Thanks!
