### ISSUE TITLE
Can you add the ability to click to collapse comments?

### ISSUE THREAD

**Issue by jazir5** [aeharding/wefwef#237]
I very much so dislike swipe gestures, could you add the ability to click to collapse comments like Boost for Reddit had?

**Comment by rahulakrishna** [comment]
What do you mean? Doesn't this already exist? Can you provide your device info? Also can you post a screen recording or something?

**Comment by jazir5** [comment]
Wow that is so weird, it has never worked before until now. I'm not sure if it was a bug that was unintentionally fixed, or if my phone was glitching out, but I've attempted to collapse comments by tapping for over a week now, and this is the first night it has.
