### ISSUE TITLE
[Feature Request] Rumble feedback for various actions

### ISSUE THREAD

**Issue by iodream** [aeharding/wefwef#241]
Apollo used to vibrate for various actions you did like swipe-upvotes and downvotes on comments, saving a comment or post and many others. Would this be possible in the form of a webapp? 

I think these were very nice in giving you instant feedback that an action has been performed without looking for other indicators such as color changing. Are these features planned? Thank you for such a great and rapidly developed app!

**Comment by aeharding** [comment]
Its kinda possible with Android, but the vibration API is just a standard time-based API and not haptic based.

This may be possible in a native app wrapper, but not right now, so closing for now.
