### ISSUE TITLE
Double submit issues

### ISSUE THREAD

**Issue by rsammelson** [aeharding/wefwef#247]
When commenting (and probably posting) with a poor connection, sometimes a post failed error is received and the comment window stays open, but the comment is actually submitted.

**Comment by aeharding** [comment]
Pretty sure this is a lemmy.world issue. I've seen this too and lemmy.world returns non-200 even when comment is submitted.

So there's not too much we can do here, it should be resolved upstream.

**Comment by rsammelson** [comment]
Could you query to check if a comment with the same content was made recently? I thought I was a timeout issue though so if they are really returning an error code I guess that's definitely their (understandable) problem.

**Comment by aeharding** [comment]
We could but then that request could also fail 🙃

I don't think it's worth worrying about (for now). The lemmy team is actively working on this (sorry I don't have the issue #)
