### ISSUE TITLE
Bug: Composer text gets written behind the system clock

### ISSUE THREAD

**Issue by chenew** [aeharding/wefwef#251]
This is a bug I just noticed in the most recent release (0.12.0), but it could have been in earlier releases that I didn’t notice.

When replying to a comment that has 10 lines or more, the composer screen gets pushed up to the clock section and the text is written behind the clock and the signal/battery info. With iPhones with the island (or maybe even the notch) the text gets written behind the island and several words won’t be visible at all (the screenshot doesn’t show the dynamic island). I’ve tested this on comments less than 10 lines and it doesn’t produce this issue.

iPhone 14 Pro
iOS 16.5.1
Link to reproduce: https://lemmy.world/comment/801047

Screenshot:
![IMG_5195](https://github.com/aeharding/wefwef/assets/5931313/92d83666-3423-49e2-bff5-981e76a097a4)

**Comment by aeharding** [comment]
This has been a bug for a while. It's because safari is trying to be smart for poorly designed webpages, and it ends up being terrible for us :(

**Comment by bdonvr** [comment]
Duplicate #75 https://github.com/aeharding/wefwef/issues/75
