### ISSUE TITLE
Prebuilt ARM Docker image doesn't work on M1 Mac running Asahi

### ISSUE THREAD

**Issue by entropicdrifter** [aeharding/wefwef#253]
I'm running a wefwef instance off of an M1 Mac Mini running Asahi Linux. After trying and failing to get a prebuilt image to work, I was able to build it from the github repo instead.

It'd be nice if the ARMv8 image worked on M1 Macs.

**Comment by AvatarMomo** [comment]
Prebuilt image is not running on oracle ARM server as well. Container is restarting without any log output.

This is the docker compose used

`version: '3.3'

services:
    wefwef:
      image: ghcr.io/aeharding/wefwef:latest
      container_name: "wefwef"
      restart: unless-stopped
      environment:
        - CUSTOM_LEMMY_SERVERS="lemmy.world"
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Berlin
      ports:
        - 5314:5314
      labels:
        com.centurylinklabs.watchtower.enable: "true"
`

**Comment by aeharding** [comment]
cc @Crazybus @joshdick

**Comment by jonesetc** [comment]
This looks as straightforward as building for `linux/arm64` instead of `linux/arm/v8` as seen in PR https://github.com/aeharding/wefwef/pull/266

**Comment by aeharding** [comment]
This should be fixed by #266 (thanks @jonesetc)
