### ISSUE TITLE
Cannot go to a remote user from the search page, as "@" is URI encoded as "%40" for the user search suggestion.

### ISSUE THREAD

**Issue by bdonvr** [aeharding/wefwef#265]
![image](https://github.com/aeharding/wefwef/assets/10774527/a1d6b913-b545-416b-80d6-e5cefba231fb)

This appears to be a mistake in `/src/features/search/SearchOptions.tsx` where the variable `searchURI` is used for the user search result and not the other types. 

I have already fixed this and can submit a PR for it if that's alright with you, as per https://github.com/aeharding/wefwef/discussions/180 :)

https://github.com/bdonvr/wefwef/commit/e82253986880c51e37b1fe30dc61bc6599450a7f

**Comment by bdonvr** [comment]
https://github.com/aeharding/wefwef/pull/274

**Comment by bdonvr** [comment]
See https://github.com/aeharding/wefwef/pull/278

**Comment by aeharding** [comment]
Should be fixed now for next release!
