### ISSUE TITLE
Instead of comment/hide on swipe, can we have an option for comment/save on swipe?

### ISSUE THREAD

**Issue by dobbsrx** [aeharding/wefwef#275]
So when scrolling, the pull to the right swipe does upvote then down vote

pull to the left swipe is similar but does a comment then hide post

can we change (or allow the option to change) the “hide post” to “save post”?

I’d be happy to just do it in my instance in docker to try it if I knew where the code was to change… is there a /config directory that can be linked to an external volume?

**Comment by mdecourcy** [comment]
Related: #242 #64

**Comment by aeharding** [comment]
Thanks for the issue! But I'm closing as a duplicate.
