### ISSUE TITLE
[bug] Not able to scroll through to the top at once after clicking posts button

### ISSUE THREAD

**Issue by Rahularyan2211** [aeharding/wefwef#323]
I have noticed this bug on Android, iOS, and Windows.. it is most prominent in Windows but can be seen on Android and iOS...
Here is a video on Windows showcasing the bug:
https://www.youtube.com/watch?v=qKROGr3LCAM

**Comment by aeharding** [comment]
Closing at fixed with #323. Let me know if there's still issues :)
