### ISSUE TITLE
Add support for new sorting options - Top Hour, Top Six Hours and Top Twelve Hours

### ISSUE THREAD

**Issue by GitBarns** [aeharding/wefwef#34]
basically the title, recently these sort options have been added and I'd love to see them in WefWef as well

https://github.com/LemmyNet/lemmy/pull/3161 for more info

**Comment by aeharding** [comment]
Thanks very much for the issue!

**Comment by asolidtime** [comment]
Is there currently an option to sort by top for any amount of time?

**Comment by aeharding** [comment]
Not currently - just the general "top" is implemented

**Comment by burakcan** [comment]
I think lemmy-js-client needs an update before implementing this. 
https://github.com/LemmyNet/lemmy-js-client/issues/155

**Comment by rsammelson** [comment]
@GitBarns is this completed now?

**Comment by GitBarns** [comment]
Yes, thank you!
