### ISSUE TITLE
Attempting to swipe back to the communities page from the posts page keeps bringing up the posts page

### ISSUE THREAD

**Issue by PawanHegde** [aeharding/wefwef#35]
Version: 0.2.2. 

I had swiped back to the list of posts and was trying to swipe back from there to the list of communities.

In the below video, I slowly swiped left to write, moved my finger back without reaching the end and then next time swiped completely from left to right. In all cases, the swipe was ending up back on the page i already was at

https://github.com/aeharding/wefwef/assets/3167291/5f90b324-836a-4eca-b723-4b384bc5e05a

**Comment by PawanHegde** [comment]
Sorry for the title edit spam 😩
I was trying to write the title on gh mobile and didn't notice that all the versions were recorded in the issue.

**Comment by aeharding** [comment]
Thanks for the bug report!

**Comment by aeharding** [comment]
Hi there, I tried to reproduce this but I am having issues reproducing. Can you provide steps for reproduction after force quitting the app? And your iOS version? Thanks very much!

**Comment by PawanHegde** [comment]
Updated to 0.3.0 and I can't reproduce the bug either. FWIW, I'm on iOS 16.5.1.

**Comment by aeharding** [comment]
OK, let me know if you can and I'll reopen.
