### ISSUE TITLE
Allow hiding posts

### ISSUE THREAD

**Issue by ShaneK** [aeharding/wefwef#45]
I know this isn’t a thing natively supported by Lemmy, but the inability to hide posts really bothers me. The app could internally remember posts that have been hidden and just not display them to the user.

This might mess with paging, but should generally be alright.

**Comment by aeharding** [comment]
Hi Shane! Thanks for the report.

Can you bullet point your typical experience for hiding posts? Do you typically tap through some posts in a feed then click the ellipse in the header to hide posts?

When posts are hidden, do you have it set to affect viewing subreddits? Should posts hidden in the main feeds also be hidden in community/subreddit feeds? Should hidden posts be permanently persisted, or just temporarily?

I'm trying to figure out what a good MVP looks like here :)

**Comment by ShaneK** [comment]
I'd really like the Apollo experience, swipe far left to hide a post, hidden post section on my profile page where I can unhide in the same way (swipe gestures were configurable, but this is how I had them set).

Hidden posts would be hidden everywhere except in the hidden posts section. This allowed me to not have to see the same stuff I'd already seen really easily.

I get if this isn't a priority or something everyone wants, but I really used this feature a ton in Apollo.

**Comment by aeharding** [comment]
Perfect, thanks for the explanation!

**Comment by burakcan** [comment]
I am implementing this now. I got the basic functionality working, will open a pr after a little polishing.

**Comment by teddyursa** [comment]
My preferred 'hiding' experience is simply scrolling past like in Apollo. Once it's gone off the top of my phone screen ,it's marked grey [instead of white text] and upon refresh...he gone!

This functionality would be amazing, and make wefwef the king app on iOS imo.

**Comment by aeharding** [comment]
> > My preferred 'hiding' experience is simply scrolling past like in Apollo. Once it's gone off the top of my phone screen ,it's marked grey [instead of white text] and upon refresh...he gone!
> 
> This was not default behavior, FYI. I think you’d find many confused users if this was the default behavior.

It's not, but it is something we plan on implementing as an option. @burakcan has done a lot of great work to ensure you can hide literally millions of posts locally without slowing the device down, which is the headwork for that

**Comment by ShaneK** [comment]
This was implemented beautifully, well done. Thank you

**Comment by daniel-l** [comment]
As an addendum: is there any way to *unhide* previously hidden posts? I couldn't find any way to show a hidden post again, other than having it bookmarked before hiding it.

**Comment by ShaneK** [comment]
> As an addendum: is there any way to *unhide* previously hidden posts? I couldn't find any way to show a hidden post again, other than having it bookmarked before hiding it.

Go to your profile view and at the top there's a button that says hidden posts, you can click on that to view all of your hidden posts. You can then unhide them by clicking on the menu button and hitting unhide, or swiping.

**Comment by daniel-l** [comment]
> > As an addendum: is there any way to _unhide_ previously hidden posts? I couldn't find any way to show a hidden post again, other than having it bookmarked before hiding it.
> 
> Go to your profile view and at the top there's a button that says hidden posts, you can click on that to view all of your hidden posts. You can then unhide them by clicking on the menu button and hitting unhide, or swiping.

Wow, totally missed that. Thanks a lot!
