### ISSUE TITLE
Allow easy definition of default server - and even perhaps allowing only one server for logging in.

### ISSUE THREAD

**Issue by bdonvr** [aeharding/wefwef#47]
Hi there! I'm running WefWef alongside my Lemmy instance. I'd really like to easily be able to have it only connect to my instance, as I only intend my hosting of wefwef to be used by my own users. Perhaps as a command line argument.

**Comment by bdonvr** [comment]
By changing the built in instance lists and the "other" option in the source I was able to achieve an instance locked WefWef.

I now host it alongside my Lemmy instance. https://app.thelemmy.club

**Comment by aeharding** [comment]
So I have implemented the ability to add custom server(s) in #51! It defaults to the first server's feed when visiting the app logged out. :)

However I decided to opt out of locking it down. Might add in the future, but right now, I think people should expect to log into their lemmy server from a given wefwef community deployment.
