### ISSUE TITLE
Saving and viewing saved posts/comments?

### ISSUE THREAD

**Issue by sanicki** [aeharding/wefwef#57]
Is there a way to view posts and comments which have been saved?

I expect to see "Saved" under "Posts" and "Comments" like the Lemmy web app, but can't find it anywhere in Wefwef.

Lemmy web app:
![Screenshot_20230628-215132-01.jpeg](https://github.com/aeharding/wefwef/assets/6764844/1c59b851-a9bb-4e60-a5f8-07f24cc3e913)

Wefwef:
![Screenshot_20230628-215840.png](https://github.com/aeharding/wefwef/assets/6764844/15fb8897-aafa-46d6-b5a3-a82add91c1e9)

**Comment by aeharding** [comment]
Saving and viewing saved posts/comments is coming! Thanks for making the issue, I forgot to!

**Comment by xBracey** [comment]
@aeharding Just a heads up, I've put a PR in for this if you haven't already started it!

**Comment by aeharding** [comment]
@xBracey, nope I was actually planning on working on this today. I'll review this when I can
