### ISSUE TITLE
Double tap search button to start search

### ISSUE THREAD

**Issue by kra-mo** [aeharding/wefwef#61]
Tapping the search button while already in the search tab should focus the search bar for easier navigation.

**Comment by aeharding** [comment]
I love little touches like this!

**Comment by httpjamesm** [comment]
Same with long pressing. Long presses/double taps on any of the bottom icons should perform the "obvious" action

**Comment by ScottBurfieldMills** [comment]
If this is still open in a couple days then I will implement it!
