### ISSUE TITLE
Compact post feed view

### ISSUE THREAD

**Issue by aeharding** [aeharding/wefwef#65]
Compact post view placeholder. I'm going to start working on this right after I finish editing comments.

**Comment by ryblogs** [comment]
Just saw compact view in 0.8.0... awesome & thank you!

Possible you could give the option for reverse compact? i.e. thumbnails on right side?

**Comment by aeharding** [comment]
Yup, that's coming. I'll make a future issue iterating all of the settings. Closing this one though!
