### ISSUE TITLE
Open external links in the default browser app instead of always chrome (Android)

### ISSUE THREAD

**Issue by kturques** [aeharding/wefwef#68]
wefwef is amazing and is working very well for me on Android. One issue is that it uses the internal Chrome browser to open external links and may not be using Android's settings. Chrome for Android has no plugin support and links are ad riddled compared to Firefox with uBlock origin and private mode by default. Is there a chance to use the default user selected browser, instead of always Chrome?

**Comment by httpjamesm** [comment]
I believe this is an API limitation. Wefwef already sets the target blank flag on embedded links. 

If you use Brave browser, it will open links in a Brave tab.

**Comment by aeharding** [comment]
Hi! Yeah, unfortunately there's not much we can do here without going into the stores.

But that's a whole other can of worms :)
