### ISSUE TITLE
Community links double nested <a>

### ISSUE THREAD

**Issue by aeharding** [aeharding/wefwef#73]
Help welcome on this. But it's not a trivial bug (at least, for me). I've spent too much time in mdast/unist/unified land and a set of new eyes would be appreciated, especially if you have experience with syntax tree parsing.

https://wefwef.app/search/lemmy.world/c/asklemmy@lemmy.ml/comments/614681

Basically you get nested anchor tags because of the custom built plugin ([buildCommunityPlugin.tsx](https://github.com/aeharding/wefwef/blob/main/src/features/shared/markdown/buildCommunityPlugin.tsx)).

This code for markdown parsing of Lemmy community links is super hacky. Basically I hack the gfm autolinker to NOT parse "email-like" strings that start with !, otherwise because it always runs first, it will parse before the custom plugin can run.

Then the custom plugin runs, and it's hacky and needs refactor because it creates nested anchor elements.

see:

<img width="294" alt="Screenshot 2023-06-29 at 12 32 10 PM" src="https://github.com/aeharding/wefwef/assets/2166114/4417f310-9557-4c49-8227-21f5d52e0a60">
<img width="613" alt="Screenshot 2023-06-29 at 12 32 07 PM" src="https://github.com/aeharding/wefwef/assets/2166114/46a7652f-7c26-4340-85ea-9d0f18bf6a1c">
<img width="563" alt="Screenshot 2023-06-29 at 12 32 02 PM" src="https://github.com/aeharding/wefwef/assets/2166114/084b21dd-3352-4011-8b53-ac448ec15329">

**Comment by denkristoffer** [comment]
Removing the plugin from remark still renders the /c/futurama link for me, but the top level links are gone. I'd like to look at `mdast-util-gfm-autolink-literal-lemmy` package but it doesn't seem to be on GitHub. Is it?

<img width="364" alt="Screenshot 2023-06-30 at 12 11 07" src="https://github.com/aeharding/wefwef/assets/219017/c478daf0-031c-416d-ba30-031761f562c9">

**Comment by aeharding** [comment]
Hi @denkristoffer, thanks for taking a look at it!

The `-lemmy` fork is here: https://github.com/aeharding/mdast-util-gfm-autolink-literal-lemmy/commit/39953aed8d2461c3f7d1ee57dfaf823dab518af5

You're totally on to something. It looks like the user of that comment manually linked it with markdown, but the custom community plugin is relinking it, causing the nested anchors.

**Comment by rideron89** [comment]
I don't have experience syntax tree parsing, but would a potential solution be one that only creates a new link node when the `parent` _isn't_ a link? Or maybe creates a new link node as long as the parent isn't a link with the same URL/link/href?

**Comment by aeharding** [comment]
Yeah - It's probably something like that @rideron89.

**Comment by rideron89** [comment]
@denkristoffer are you working on this? If not, I can create a PR for this. But I don't want to step on your toes.

**Comment by denkristoffer** [comment]
@rideron89 No go right ahead 😄
