### ISSUE TITLE
Respect Lemmy user setting for showing NSFW content

### ISSUE THREAD

**Issue by bdonvr** [aeharding/wefwef#76]
WefWef seems to filter out NSFW communities, with no option to stop doing so.

Compare a community search on Lemmy-UI to WefWef:

![IMG_1147](https://github.com/aeharding/wefwef/assets/10774527/a176a05b-8635-43ee-b51e-25c8bed63c67)
![IMG_1148](https://github.com/aeharding/wefwef/assets/10774527/0a96d2f9-8e21-46bc-9539-fc4a40bd7d02)

**Comment by aeharding** [comment]
Ah, thanks for the issue. Search request probably doesn't have jwt attached.
