### ISSUE TITLE
PWA IOS: no app icon

### ISSUE THREAD

**Issue by RocketRide9** [aeharding/wefwef#87]
![6857D219-EF84-4A4D-92E3-73A0477A7220](https://github.com/aeharding/wefwef/assets/70429241/847fa3bb-6668-43f2-98f9-6d9bd77300b4)

**Comment by gregside** [comment]
Interesting, I recreate this only when I select "Add to Home Screen", but back out before saving and then press "Add to Home Screen" again.

This doesn't seem to happen with other websites.

**Comment by RocketRide9** [comment]
> What's your iOS version?

15.3
I use iPhone se

**Comment by aeharding** [comment]
Ah. Added in iOS 15.4.

Will need to add back `apple-touch-icon`

https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes

**Comment by aeharding** [comment]
Should be resolved in 0.8.0
